dragonflyoss/console

.editorconfig, .gitignore, .prettierignore, .prettierrc, .umirc.ts, README.md, package.json, src/global.css, src/layouts/index.jsx, src/pages/config/index.jsx, src/pages/document.ejs, src/pages/index.less, src/pages/index.tsx, tsconfig.json, typings.d.ts
=> init front framework

.github/CODEOWNERS, .github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/custom.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/PULL_REQUEST_TEMPLATE.md
=> chore: add issue template

package.json
=> feat: add jsonwebtoken

src/global.css
=> feat: change header font-size

src/pages/installation/index.tsx
=> docs: change docs link

.github/dependabot.yml
=> chore: add dependabot actions

.github/workflows/ci.yml
=> chore: add ci actions

src/pages/cdn/index.less, src/pages/cdn/index.tsx, src/pages/scheduler/index.less, src/pages/scheduler/index.tsx
=> fix #54 cluster add pagination

src/pages/cdn/index.less, src/pages/cdn/index.tsx, src/pages/scheduler/index.less, src/pages/scheduler/index.tsx
=> delete invalid codes and optimized styles

.umirc.ts
=> Change proxy address

.github/workflows/check-size.yaml, .github/workflows/ci.yaml, .github/workflows/codeql-analysis.yaml, .github/workflows/e2e.yaml, .github/workflows/lint.yaml, .github/workflows/release.yml, .gitignore, .husky/commit-msg, .lintstagedrc.js, cypress/e2e/home.cy.js, package.json
=> feat: add github actions

codecov.yml
- Add patch rules to `codecov.yaml`.
=> chore: add path rules to codecov.yaml

pages/cluster/index.tsx, pages/job/index.tsx, pages/login/index.tsx, pages/security/index.tsx, pages/user/index.tsx
initialize project layout
https://sourcegraph.com/github.com/pmndrs/threejs-journey/-/tree/pages/shaders
=> feat:initialize project layout

lib/api.ts
- Fetch with credentials include.
=> feat: fetch with credentials include

pages/signin/index.tsx
signin page change password verification
=> feat:signin page change password verification

package.json
=> chore: add export script to package.json

components/signin/index.tsx
=> feat:change signin page title

src/layouts/main.tsx, src/lib/api.ts
=> fix: api url is invaild when REACT_APP_API_URL is empty

package.json
=> feat: change build path to dist

public/index.html
=> feat: add description and keywords to link

public/images/login/dragonfly.svg
=> chore: change dragonfly.svg in login images

src/components/clusters/index.tsx, src/components/clusters/show.tsx, src/components/profile/index.tsx, src/components/signup/index.tsx
=> feat: change copy

src/components/clusters/show.tsx
=> feat: change shceduler cluster table

src/components/clusters/edit.tsx, src/components/clusters/new.tsx, src/components/developer/tokens/edit.tsx, src/components/developer/tokens/new.tsx, src/components/profile/index.tsx, src/components/signin/index.tsx, src/components/signup/index.tsx
=> fix: modify form regular expression

src/components/clusters/show.tsx, src/lib/api.ts
=> fix: search schedulers and seed peers with page and per_page

src/components/clusters/index.tsx, src/components/clusters/show.tsx
=> fix: search scheduler and seed peers when delete table row

src/components/clusters/edit.tsx, src/components/clusters/index.tsx, src/components/clusters/new.tsx, src/components/developer/tokens/edit.tsx, src/components/developer/tokens/index.tsx, src/components/developer/tokens/new.tsx, src/components/menu/index.tsx, src/components/profile/index.tsx, src/components/schedulers/show.tsx, src/components/seed-peers/show.tsx, src/components/signin/index.tsx, src/components/signup/index.tsx, src/components/users/index.tsx
=> fix: change all page names

src/components/clusters/edit.tsx
=> fix: show cluster name and id in updating cluster

src/components/clusters/show.tsx
=> fix: fix show cluster pagination function

src/components/clusters/index.tsx, src/components/menu/index.tsx, src/components/users/index.tsx, src/lib/api.ts, src/lib/constants.ts
=> fix: Add user page pagination function

src/components/developer/tokens/index.tsx, src/lib/api.ts, src/lib/constants.ts
=> fix: Add pagination function of Personal access tokens page

src/components/clusters/index.tsx, src/components/clusters/show.tsx, src/components/developer/tokens/index.tsx, src/components/users/index.tsx, src/lib/constants.ts
=> fix: constants file add page size constant

src/components/clusters/index.tsx, src/components/clusters/show.tsx, src/components/developer/tokens/index.tsx, src/components/users/index.tsx
=> fix: Modify pagination and Personal access tokens without token display

src/components/signin/index.tsx, src/components/signup/index.tsx
=> fix: SignIn and SignUp Name verification

src/components/developer/tokens/edit.tsx, src/components/developer/tokens/new.tsx
=> feat: Add cluster checkbox in scopes to personal access token

src/components/clusters/index.tsx, src/lib/api.ts
=> fix: Change error message

src/components/menu/index.tsx, src/components/users/index.tsx, src/layouts/main.tsx
=> fix: Fix update role error

src/components/developer/tokens/edit.tsx, src/components/developer/tokens/new.tsx
=> feat: Add scopes prompt in personal access token

src/components/clusters/edit.module.css, src/components/clusters/edit.tsx, src/components/clusters/index.module.css, src/components/clusters/index.tsx, src/components/clusters/information.module.css, src/components/clusters/information.tsx, src/components/clusters/new.module.css, src/components/clusters/new.tsx, src/components/clusters/show.tsx, src/lib/api.ts
=> Add multi idc and change the scopes ui of the show cluster page

src/components/clusters/edit.tsx, src/components/clusters/new.tsx, src/components/developer/tokens/edit.tsx, src/components/developer/tokens/new.tsx, src/components/profile/index.tsx, src/components/signin/index.tsx, src/components/signup/index.tsx
=> feat: Optimize validate message

src/components/clusters/edit.module.css, src/components/clusters/edit.tsx, src/components/clusters/new.module.css, src/components/clusters/new.tsx, src/components/developer/tokens/edit.tsx, src/components/developer/tokens/new.tsx
=> fix: change form ui

src/components/clusters/index.tsx, src/components/clusters/show.tsx, src/lib/api.ts, src/lib/utils.ts
=> fix: fix schedule and seed peer table

src/components/developer/tokens/index.tsx, src/lib/api.ts
=> fix: change personal access tokens page sorting and pagination

src/components/users/index.tsx, src/lib/api.ts
=> fix: change users page pagination

src/components/clusters/index.tsx, src/components/clusters/show.tsx, src/components/job/preheats/new.tsx, src/lib/api.ts
=> fix: change cluster page pagination

src/components/clusters/index.tsx, src/components/clusters/show.tsx, src/components/developer/tokens/index.tsx, src/components/insight/peer/index.tsx, src/components/users/index.tsx
=> fix: build error

src/components/clusters/edit.tsx, src/components/clusters/new.tsx, src/components/developer/tokens/new.tsx, src/components/job/preheats/new.tsx, src/components/menu/index.tsx
=> fix: multiple input box

src/components/job/preheats/index.tsx, src/lib/api.ts
=> fix: Job uses server's pagination

src/components/clusters/index.tsx
=> fix: If there is no cluster console will panic will

cypress/e2e/404.cy.ts, cypress/e2e/signin.cy.ts, cypress/e2e/signup.cy.ts, cypress/fixtures/api/signup.json
signup refer to  
https://sourcegraph.com/github.com/PostHog/posthog@d056580b3fc8f505ac7a8a9fe0a7888fd34e6ba6/-/blob/cypress/e2e/signup.cy.ts?L42:5
=> feat: add signup and 404 e2e test

cypress/e2e/update-cluster.cy.ts, cypress/fixtures/api/clusters/cluster/update-cluster.json, package.json, src/components/clusters/edit.tsx
filename refer to: https://sourcegraph.com/github.com/onap/sdc@b658a1b74292ad8e58bb20f5ac4271062299a692/-/blob/catalog-ui/cypress/fixtures/service-proxy-tabs/update-rule-result.json
cy:run refer to: https://docs.cypress.io/guides/guides/launching-browsers#You-can-also-launch-Electron-headed
=> feat: add edit cluster page e2e test

cypress/e2e/profile.cy.ts, cypress/fixtures/api/update-user.json, src/components/clusters/edit.tsx, src/components/clusters/new.tsx, src/components/developer/tokens/edit.tsx, src/components/developer/tokens/new.tsx, src/components/menu/index.tsx, src/components/profile/index.module.css, src/components/profile/index.tsx, src/lib/api.ts
=> feat: add profile page e2e test

cypress/e2e/cluster/cluster.cy.ts, cypress/e2e/create-cluster.cy.ts, cypress/e2e/update-cluster.cy.ts, cypress/fixtures/api/clusters/cluster/cluster.json, cypress/fixtures/api/clusters/cluster/delete-cluster.json, cypress/fixtures/api/clusters/cluster/delete-clusters.json, cypress/fixtures/api/clusters/cluster/update-cluster.json, cypress/fixtures/api/clusters/clusters.json, cypress/fixtures/api/clusters/create-cluster.json, cypress/fixtures/api/clusters/search-cluster.json, src/components/clusters/edit.tsx, src/components/clusters/information.module.css, src/components/clusters/information.tsx, src/components/clusters/new.tsx, src/components/clusters/show.tsx, src/components/insight/peer/index.tsx, src/lib/api.ts
=> feat: remove concurrent_piece_count in cluster

cypress/e2e/job/preheat.cy.ts, cypress/fixtures/preheats/failure-preheat.json, cypress/fixtures/preheats/pending-preheat.json, cypress/fixtures/preheats/success-preheat.json, src/components/job/preheats/index.tsx, src/components/job/preheats/show.module.css, src/components/job/preheats/show.tsx, src/lib/api.ts
=> feat: add preheat page e2e test

cypress/e2e/job/create-preheat.cy.ts, cypress/e2e/job/preheat.cy.ts, cypress/e2e/job/preheats.cy.ts, cypress/fixtures/preheats/create-preheat.json, src/components/job/preheats/new.tsx
=> feat: add new preheat page e2e test

cypress/e2e/menu.cy.ts, package.json, src/components/menu/index.tsx
=> feat: add menu e2e test

src/components/job/preheats/show.tsx, src/lib/api.ts
Fixes https://github.com/dragonflyoss/Dragonfly2/issues/3033.
=> fix: An error occurs when the show preheat page headers are empty

cypress/e2e/job/preheats/create-preheat.cy.ts, cypress/fixtures/job/preheats/create-preheat.json, cypress/fixtures/job/preheats/failure-preheat.json, cypress/fixtures/job/preheats/failure-preheats.json, cypress/fixtures/job/preheats/pagination-preheats.json, cypress/fixtures/job/preheats/pending-preheat.json, cypress/fixtures/job/preheats/pending-preheats.json, cypress/fixtures/job/preheats/preheats.json, cypress/fixtures/job/preheats/success-preheat.json, cypress/fixtures/job/preheats/success-preheats.json, src/components/job/preheats/new.tsx, src/components/job/preheats/show.tsx, src/lib/api.ts
=> feat: Modify the preheat parameter to filteredQueryParams

cypress/e2e/clusters/clusters.cy.ts, cypress/e2e/developer/tokens/tokens.cy.ts, cypress/e2e/job/preheats/preheats.cy.ts, cypress/e2e/schedulers/schedulers.cy.ts, cypress/e2e/seed-peers/seed-peers.cy.ts, cypress/e2e/users/users.cy.ts, src/components/clusters/index.tsx, src/components/clusters/show.tsx, src/components/developer/tokens/index.tsx, src/components/job/preheats/index.tsx, src/components/users/index.tsx, src/lib/utils.ts
https://github.com/dragonflyoss/console/pull/353/files#diff-da10bcc7d8dff796f50c9358a7268eb5abd2c50f460aecc4b2be1c691a966224R7
refer to: https://sourcegraph.com/github.com/backstage/backstage@7ff2e4257f178aff9b1055a2633337637083cde9/-/blob/plugins/lighthouse/src/utils.ts?L24:1-24:44
use
refer to: 
https://sourcegraph.com/github.com/backstage/backstage@7ff2e4257f178aff9b1055a2633337637083cde9/-/blob/plugins/lighthouse/src/components/AuditList/index.tsx?L52
=> feat: change pagination

config-overrides.js, cypress/e2e/clusters/update-cluster.cy.ts, cypress/e2e/developer/tokens/update-token.cy.ts, src/components/clusters/edit.tsx, src/components/clusters/show.tsx, src/components/developer/tokens/index.tsx
=> fix: edit cluster page problem

cypress/e2e/clusters/cluster.cy.ts, cypress/e2e/clusters/update-cluster.cy.ts, cypress/fixtures/clusters/cluster/cluster.json, cypress/fixtures/clusters/cluster/delete-cluster.json, cypress/fixtures/clusters/cluster/delete-clusters.json, cypress/fixtures/clusters/cluster/update-cluster.json, cypress/fixtures/clusters/clusters.json, cypress/fixtures/clusters/create-cluster.json, cypress/fixtures/clusters/search-cluster.json, public/index.html, src/components/clusters/information.module.css, src/components/clusters/information.tsx
=> feat: clusters page shows multiple idc CIDR and hostname

cypress/e2e/developer/tokens/tokens.cy.ts, cypress/e2e/job/preheats/create-preheat.cy.ts, cypress/e2e/job/preheats/preheat.cy.ts, cypress/e2e/job/preheats/preheats.cy.ts, cypress/e2e/schedulers/schedulers.cy.ts, cypress/e2e/seed-peers/seed-peer.cy.ts, cypress/e2e/seed-peers/seed-peers.cy.ts, cypress/fixtures/job/preheats/failure-preheat.json, src/components/clusters/edit.tsx, src/components/clusters/index.tsx, src/components/clusters/show.tsx, src/components/developer/tokens/edit.tsx, src/components/developer/tokens/index.tsx, src/components/insight/peers/index.tsx, src/components/job/preheats/index.tsx, src/components/job/preheats/new.tsx, src/components/job/preheats/show.tsx, src/components/menu/index.tsx, src/components/profile/index.tsx, src/components/schedulers/show.tsx, src/components/seed-peers/show.tsx, src/components/users/index.tsx, src/lib/api.ts, src/lib/utils.ts
=> preheat error log  is not displayed

cypress/e2e/clusters/create-cluster.cy.ts, cypress/e2e/clusters/update-cluster.cy.ts, src/components/clusters/edit.tsx, src/components/clusters/new.tsx
=> feat: Change the Cluster parameter seed Peer Load Limit to 0-50000

cypress/e2e/clusters/create-cluster.cy.ts, src/components/clusters/new.tsx
…efault value of peerLoadLimit to 200
=> feat: Change the default of seedPeerLoadLimit to 2000 and the default of peerLoadLimit to 200

src/components/clusters/index.module.css, src/components/clusters/index.tsx
=> fix: cluster card layout

src/components/clusters/edit.tsx
=> feat: change edit cluster

cypress.config.ts, cypress/e2e/job/preheats/create-preheat.cy.ts, cypress/fixtures/job/preheats/create-preheat.json, cypress/fixtures/job/preheats/failure-preheat.json, cypress/fixtures/job/preheats/failure-preheats.json, cypress/fixtures/job/preheats/pagination-preheats.json, cypress/fixtures/job/preheats/pending-preheat.json, cypress/fixtures/job/preheats/pending-preheats.json, cypress/fixtures/job/preheats/preheats.json, cypress/fixtures/job/preheats/success-preheat.json, cypress/fixtures/job/preheats/success-preheats.json, src/components/job/preheats/index.tsx, src/components/job/preheats/new.tsx, src/components/job/preheats/show.tsx, src/lib/api.ts
=> feat: Change preheat field

src/components/clusters/show.tsx
Fixed https://github.com/dragonflyoss/Dragonfly2/issues/3538.
=> fix: number of active schedulers misspell

src/components/clusters/show.tsx
=> fix: Change delete button text

src/components/circular-progress.tsx, src/components/clusters/index.tsx, src/components/clusters/show.tsx, src/components/job/task/clear/index.module.css, src/components/job/task/clear/index.tsx
=> fix: Paging bug

cypress/e2e/job/preheats/preheat.cy.ts, src/components/job/preheats/index.tsx, src/components/job/preheats/show.tsx, src/components/job/task/clear/index.tsx, src/components/job/task/executions/index.tsx, src/components/job/task/executions/show.tsx, src/lib/utils.ts
=> feat: Display based on local time zone

package.json
This pull request includes a small change to the `package.json` file. The change updates the browser support list by increasing the minimum usage percentage for production environments from 0.2% to 0.5%.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L89-R89): Updated the `browserslist` configuration for production to ">0.5%" from ">0.2%".
=> chore: optimize browserslist for production

cypress/e2e/peers/peers.cy.ts, src/components/clusters/peers/index.tsx, src/components/clusters/schedulers/index.tsx, src/components/clusters/seed-peers/index.tsx, src/components/loading-button.tsx
=> fix: peer e2e error

cypress/e2e/clusters/clusters.cy.ts, cypress/e2e/job/task/clear.cy.ts, cypress/e2e/menu/menu.cy.ts, cypress/e2e/schedulers/scheduler.cy.ts, cypress/e2e/schedulers/schedulers.cy.ts, cypress/e2e/seed-peers/seed-peer.cy.ts, cypress/e2e/seed-peers/seed-peers.cy.ts, src/App.tsx
This pull request mainly updates the console's default light mode to dark mode.
=> feat: Changed to dark mode by default

cypress/e2e/clusters/cluster.cy.ts
=> chore: Change cluster e2e test annotation

src/components/clusters/index.module.css, src/components/clusters/index.tsx
=> chore: optimizing cluster CSS

src/components/clusters/information.module.css, src/components/clusters/information.tsx
=> chore: optimizing cluster information

src/components/clusters/schedulers/index.module.css, src/components/clusters/schedulers/index.tsx
=> chore: optimizing schedulers

cypress/e2e/job/task/clear.cy.ts, cypress/e2e/menu/menu.cy.ts, src/components/dark-layout.module.css, src/components/dark-layout.tsx, src/components/menu/index.tsx, src/components/signin/index.tsx, src/components/signup/index.tsx
=> chore: change dark layout

cypress/e2e/signin/signin.cy.ts, src/components/menu/index.tsx, src/components/signin/index.module.css, src/components/signin/index.tsx
=> chore: change signin

package.json
=> chore: bump query-string version to v9.1.1

cypress/e2e/schedulers/scheduler.cy.ts, src/components/clusters/schedulers/show.tsx
=> chore: change scheduler e2e test

cypress/e2e/seed-peers/seed-peer.cy.ts, src/components/clusters/seed-peers/show.tsx
=> chore: change seed peer e2e test

cypress/e2e/clusters/clusters.cy.ts, src/components/clusters/index.module.css, src/components/clusters/index.tsx
=> chore: optimizing clusters and clusters test

cypress/e2e/clusters/create-cluster.cy.ts, src/components/clusters/new.module.css, src/components/clusters/new.tsx
=> chore: optimizing create cluster and create clusters test

cypress/e2e/404/404.cy.ts, cypress/e2e/users/users.cy.ts, src/components/404/index.tsx
=> Chore  change 404 e2e test

cypress/e2e/users/users.cy.ts, src/components/users/index.module.css, src/components/users/index.tsx
=> chore: change users

cypress/e2e/users/users.cy.ts, src/components/users/index.tsx
=> feat: add search user E2E test

package.json
=> fix: change CI error

src/components/clusters/information.module.css
=> fix: Cluster scopes title style is not effective

cypress/e2e/job/preheats/create-preheat.cy.ts, src/components/job/preheats/new.tsx
=> feat: Create preheating and add search cluster function

cypress/e2e/resource/task/execution.cy.ts, src/components/job/preheats/show.tsx, src/components/resource/task/executions/show.tsx
=> chore: change preheat error log width

src/components/audit/index.module.css, src/components/audit/index.tsx, src/components/job/preheats/index.tsx, src/components/job/preheats/new.tsx, src/components/job/preheats/show.tsx, src/components/resource/task/clear/index.tsx, src/components/resource/task/executions/show.tsx, src/index.css
=> Chore  change preheat

cypress/e2e/job/preheats/create-preheat.cy.ts, cypress/e2e/job/preheats/preheat.cy.ts, src/components/job/preheats/new.tsx, src/components/job/preheats/show.tsx
=> fix: create preheat parameter ips

cypress/fixtures/resource/task/image-manifest-url-task.json, src/components/resource/task/clear/index.tsx, src/lib/api.ts
=> chore: Modify get_image_distribution job parameters

README.md
This pull request updates the `README.md` to improve clarity and community engagement. The main changes include removing the detailed functionality overview, refining the community section, and updating links and mailing list information.
Documentation and Community section improvements:
* Removed the "Functionality Overview" section, streamlining the README and focusing on essential information.
* Updated the community section to encourage participation and clarified ways to get involved, including rewording and grouping contact options.
* Changed the GitHub Discussions link to use a reference-style link for better maintainability.
* Consolidated mailing list information under a single "Mailing Lists" heading for clarity.
* Updated the DingTalk group reference to use a code rather than a …
=> docs(README): update community involvement section

package.json
=> fix: Use relative paths to fix build issues
